### ISSUE TITLE
[ADD] Todo List Project

### ISSUE THREAD

**Issue by Anadee11** [Anadee11/WebArena#34]
- [ ] Add a readme.md file to your project.
- [x] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by pikameow420** [comment]
Hello @Anadee11 I'd like to work on this.

**Comment by SahilChandravanshi** [comment]
Hey @Anadee11 , Please assign this to me. I'd like to work on this issue

**Comment by nish-ahmd-it** [comment]
Hi @Anadee11 can u assign the task to me please ?

**Comment by meetkool** [comment]
Hey @Anadee11 , please assign this to me. I'd like to work on this on react native 

![image](https://user-images.githubusercontent.com/96396841/195548525-bdb005c7-52dd-4dbe-81a8-922df7116e40.png)

i have the code returned

**Comment by Anadee11** [comment]
Hey @pikameow420 .
Go for it!
- [ ] Add a readme.md file to your project.
- [ ] This issue was opened after seeing the issues and so no similar issues are present.

**Comment by Anadee11** [comment]
Hey! @pikameow420. 
This will be assigned to someone if you are unable to work on this. Thank you

**Comment by pikameow420** [comment]
Working on it, will upload in like 3 hours

**Comment by pikameow420** [comment]
I have made the PR

**Comment by Anadee11** [comment]
Thank you for contributing @pikameow420. Do support us by leaving a star ⭐ on the repository.
